### ISSUE TITLE
Sandbox issues when building for the Mac App Store

### ISSUE THREAD

**Issue by talldude** [johansatge/nwjs-macappstore-builder#4]
We're in the process of getting our nw.js app together for App Store submission, so we're using nwjs-macappstore-builder to build it.  We're using the special "mac app store" version of nw.js:

http://dl.nwjs.io/v0.12.3/nwjs-macappstore-v0.12.3-osx-x64.zip

We've also added the entitlements that we believe we need, but after successfully building it (everything completes successfully) when launching the app it crashes with sandbox errors - i.e.

```
Sep 18 06:02:45 Brians-MacBook-Pro kernel[0]: Sandbox: appleeventsd(50) deny file-read-metadata /Library
```

Per Apple's sandbox rules, the app data should be stored in /Library/Containers/BundleID - not /Library/Application Support/AppName - do you know if the special MAS build of nw.js takes care of that?  Is there an entitlement we need to add to the config when running nwjs-macappstore-builder that will fix this up?

I opened an issue yesterday on nw.js:

https://github.com/nwjs/nw.js/issues/3841

but realized this might be something we are overlooking when building it for the MAS using nwjs-macappstore-builder.

Thanks!

**Comment by johansatge** [comment]
Hi,

I have found a few things when running tests; it looks like the builder is not involved.

If you don't mind I will close this ticket and answer on https://github.com/nwjs/nw.js/issues/3841

Thanks !
