### ISSUE TITLE
Using --force with codesign

### ISSUE THREAD

**Issue by essingh** [johansatge/nwjs-macappstore-builder#5]
I noticed in your change long that at one point you were using --force but removed it. If we don't use force we get the error "nwjs Helper.app: is already signed". Did you discover how to sign the app without using force in this situation? ( This is related to the issue https://github.com/nwjs/nw.js/issues/3841. )  

Thanks.

**Comment by johansatge** [comment]
Hi,

is you `nwjs_path` property pointing to an app that has already been signed ?

It should point to a clean, unsigned `nwjs.app` file - like this one: http://dl.nwjs.io/v0.12.3/nwjs-macappstore-v0.12.3-osx-x64.zip (it is copied and used as a base for the built app).

I removed the `--force` option because several devs told me they had issues when signing the same app several times (random crashes, etc).

**Comment by essingh** [comment]
I did a clean install of nwjs from nwjs-macappstore-v0.12.3-osx-x64.zip.

**Comment by essingh** [comment]
I did a clean install of nwjs from nwjs-macappstore-v0.12.3-osx-x64.zip and then looked at the entitlements and it looks like nwjs.app isn't signed (the last line) which is good:

```
codesign -d -v 1 --entitlements - "/Applications/nwjs.app"

Executable=/sbin/launchd
Identifier=com.apple.xpc.launchd
Format=Mach-O thin (x86_64)
CodeDirectory v=20100 size=1570 flags=0x0(none) hashes=73+2 location=embedded
Signature size=4097
Info.plist entries=18
TeamIdentifier=not set
Sealed Resources=none
Internal requirements count=1 size=72
/Applications/nwjs.app: code object is not signed at all
```

But the error we were getting when executing nwjs-macappstore-builder is for the Helper.app:

```
Command failed: /bin/sh -c codesign --deep -s "1234567890" --entitlements "/var/folders/09/yzhfrzld6z7bnhscxt168b5h0000gn/T/nwjs_child_26c38782b8cfe2d5c6ac0d6a2976062f.xml" "/Users/sham/Desktop/AppName.app/Contents/Frameworks/nwjs Helper.app"
/Users/sham/Desktop/AppName.app/Contents/Frameworks/nwjs Helper.app: is already signed
```

So I did another clean install of nwjs from nwjs-macappstore-v0.12.3-osx-x64.zip and checked the "nwjs Helper.app" and it appears to be signed (as there isn't "code object is not signed at all" ):

```
codesign -d -v 1 --entitlements - "/Applications/nwjs.app/Contents/Frameworks/nwjs Helper.app/Contents/MacOS/nwjs Helper"

Executable=/sbin/launchd
Identifier=com.apple.xpc.launchd
Format=Mach-O thin (x86_64)
CodeDirectory v=20100 size=1570 flags=0x0(none) hashes=73+2 location=embedded
Signature size=4097
Info.plist entries=18
TeamIdentifier=not set
Sealed Resources=none
Internal requirements count=1 size=72
Executable=/Applications/nwjs.app/Contents/Frameworks/nwjs Helper.app/Contents/MacOS/nwjs Helper
Identifier=io.nwjs.nw.helper
Format=bundle with Mach-O thin (x86_64)
CodeDirectory v=20100 size=186 flags=0x2(adhoc) hashes=3+3 location=system
Signature=adhoc
Info.plist entries=20
TeamIdentifier=not set
Sealed Resources version=2 rules=12 files=0
Internal requirements count=0 size=12
```

So it appears to me that "nwjs Helper" is already signed before I ever use nwjs-macappstore-builder.

**Comment by essingh** [comment]
I'm going to go ahead and close this issue as it really isn't a nwjs-macappstore-builder issue.. Thanks for your help though, it's appreciated; as is the nwjs-macappstore-builder tool itself.

**Comment by johansatge** [comment]
Well this is strange, I have checked the [current release](http://dl.nwjs.io/v0.12.3/nwjs-macappstore-v0.12.3-osx-x64.zip) and everything looks fine.

``` bash
→ codesign -d -v 1 --entitlements - "/Applications/nwjs.app/Contents/Frameworks/nwjs Helper.app/Contents/MacOS/nwjs Helper"

Executable=/sbin/launchd
Identifier=com.apple.xpc.launchd
Format=Mach-O thin (x86_64)
CodeDirectory v=20100 size=1570 flags=0x0(none) hashes=73+2 location=embedded
Signature size=4097
Info.plist entries=18
TeamIdentifier=not set
Sealed Resources=none
Internal requirements count=1 size=72
/Applications/nwjs.app/Contents/Frameworks/nwjs Helper.app/Contents/MacOS/nwjs Helper: code object is not signed at all
```

**Comment by essingh** [comment]
I've tried this many times and mine is always signed. After searching the net on "signed adhoc" I finally came across this http://forums.macnn.com/79/developer-center/355720/how-re-sign-apples-applications-once/ .  

The second paragraph has this:

```
As it stands, code needs to be signed to work properly with the new firewall and with the Parental Controls feature. 
If a program is not signed, the system will sign it with an "ad-hoc" signature when one configures the firewall or Parental Controls to allow or deny access to that program. 
As time goes one, more and more system facilities will begin to require code to be signed (presumably this will happen with point-releases or security updates of the operating system).
```

My account is an admin account so Parental Controls are already disabled so I turned off my firewall and tried again but it is still getting signed.. So my only guess is that other "system facilities" have started requiring apps to be signed and are doing so; what's odd to me though is that this is only happening for the Helper apps and not the nwjs.app itself - as my previous post shows, nwjs.app is not signed.  

I'm running Yosemite 10.10.5, are you running an older version?

**Comment by johansatge** [comment]
Hi, sorry for the delay!

I was running `10.10.4`. I have updated today to `10.10.5` and run the same tests, it still looks fine on my machine.

**Comment by essingh** [comment]
Thanks for the followup.  

Both my colleague and I are running 10.10.5 and both of us always see the Helpers already signed with an adhoc signature; but not nwjs.app oddly enough. I have a Mac Mini that is running 10.10.3 and it too shows the Helpers already signed with adhoc.  Right now our app crashes if we sign it for MAS, but since we can't sign it without using --force, we can't be certain that the --force flag (you mentioned others said that using --force caused their apps to crash..) is not causing the crash.. So it looks like we may have to launch our app outside of MAS which is doable but not our original plan.  

Thanks again for the help you've given. It is very much appreciated.
